import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import "@/index.css";
import { Toaster } from "sonner";
import { getLocale } from "next-intl/server";
import ThemeProvider from "./_context/ThemeProvider";



export const metadata: Metadata = {
  title: {
    template: '%s - Classify',
    default: 'Classify'
  },
  // description: "Generated by create next app",
};

// export const viewport: Viewport = {
//   themeColor:[ 
//  { media: "(prefers-color-scheme: dark)", color: "#1f2937" },
//  { media: "(prefers-color-scheme: light)", color: "#f3f4f6" }
// ]}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale()
  const dir = locale === 'en' ? 'ltr' : 'rtl'

  return (
    <html lang={locale} dir={dir}>
      <body
        className={`antialiased h-screen w-screen bg-[#f3f4f6]! dark:bg-[#1f2937]!`}
      >

        <NextIntlClientProvider>
          <ThemeProvider>

            <Toaster
              position='top-center'
              dir={dir}
              toastOptions={{
                duration: 5000,
                classNames: {
                  success: `!bg-green-400 !border-green-400`,
                  loading: `!bg-[var(--color-grey-0)] !border-[var(--color-grey-200)] !text-[var(--color-grey-500)]`
                }
              }}

            />
            {children}
          </ThemeProvider>

        </NextIntlClientProvider>
      </body>
    </html>
  );
}
